version: "3.0"
services:
  web:
    image: marstrueplus/m2_apache2-php7.1.6:v1
    container_name: magento_web
    ports:
    - "9100:80"
    links:
    - db
    env_file:
    - env
    volumes:
    - ./src:/var/www/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      timeout: 15s
      retries: 5
  db:
    image: mysql:5.7
    container_name: magento_db
    volumes:
    - db-data:/var/lib/mysql
    env_file:
    - env
    ports:
    - "9101:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: magento_phpmyadmin
    ports:
    - "9102:80"
    links:
    - db
volumes:
  db-data:
  src: